### ISSUE TITLE
TypeError: Cannot read property 'pipesCount' of undefined on generate

### ISSUE THREAD

**Issue by spiritguide7** [Ziv-Barber/officegen#194]
node -v v8.0.0
npm -v4.5.0

  "dependencies": {
    "archiver": "^1.3.0",
    "async": "^2.0.1",
    "fast-image-size": "^0.1.3",
    "jszip": "^2.5.0",
    "lodash": "^4.17.4",
    "readable-stream": "~2.2.2",
    "setimmediate": "^1.0.5",
    "xmlbuilder": "^3.1.0"
  },

dump of WriteStream out:
out WriteStream {
  _writableState: 
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     finalCalled: false,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     destroyed: false,
     decodeStrings: true,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function: bound onwrite],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     bufferedRequestCount: 0,
     corkedRequestsFree: 
      { next: null,
        entry: null,
        finish: [Function: bound onCorkedFinish] } },
  writable: true,
  domain: null,
  _events: { finish: { [Function: bound onceWrapper] listener: [Function] } },
  _eventsCount: 1,
  _maxListeners: undefined,
  path: 'tmp/out.docx',
  fd: null,
  flags: 'w',
  mode: 438,
  start: undefined,
  autoClose: true,
  pos: undefined,
  bytesWritten: 0 }

after call to docx.generate ( out ):

  _stream_readable.js:545
  switch (state.pipesCount) {
               ^

TypeError: Cannot read property 'pipesCount' of undefined
    at module.exports.Readable.pipe (_stream_readable.js:545:16)
    at module.exports.ZipArchiveOutputStream._smartStream (C:\Users\Jack\Documents\nodejs\officegen-master\node_modules\compress-commons\lib\archivers\zip\zip-archive-output-stream.js:184:11)
    at module.exports.ZipArchiveOutputStream._appendBuffer (C:\Users\Jack\Documents\nodejs\officegen-master\node_modules\compress-commons\lib\archivers\zip\zip-archive-output-stream.js:82:10)
    at module.exports.ArchiveOutputStream.entry (C:\Users\Jack\Documents\nodejs\officegen-master\node_modules\compress-commons\lib\archivers\archive-output-stream.js:86:10)
    at module.exports.ZipStream.entry (C:\Users\Jack\Documents\nodejs\officegen-master\node_modules\zip-stream\index.js:138:49)
    at Zip.append (C:\Users\Jack\Documents\nodejs\officegen-master\node_modules\archiver\lib\plugins\zip.js:53:15)
    at Archiver._moduleAppend (C:\Users\Jack\Documents\nodejs\officegen-master\node_modules\archiver\lib\core.js:172:16)
    at Archiver._onQueueTask (C:\Users\Jack\Documents\nodejs\officegen-master\node_modules\archiver\lib\core.js:370:8)
    at C:\Users\Jack\Documents\nodejs\officegen-master\node_modules\async\dist\async.js:4045:9
    at process (C:\Users\Jack\Documents\nodejs\officegen-master\node_modules\async\dist\async.js:2316:17)

**Comment by liesislukas** [comment]
i just got this error with all up-to-date software. Trying to start up example with docx
```
node v8.0.0
npm 5.0.3
osx

_stream_readable.js:545
  switch (state.pipesCount) {
               ^

TypeError: Cannot read property 'pipesCount' of undefined
    at module.exports.Readable.pipe (_stream_readable.js:545:16)
    at module.exports.ZipArchiveOutputStream._smartStream (/Users/lukas/Desktop/www/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:184:11)
    at module.exports.ZipArchiveOutputStream._appendBuffer (/Users/lukas/Desktop/www/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:82:10)
    at module.exports.ArchiveOutputStream.entry (/Users/lukas/Desktop/www/node_modules/compress-commons/lib/archivers/archive-output-stream.js:86:10)
    at module.exports.ZipStream.entry (/Users/lukas/Desktop/www/node_modules/zip-stream/index.js:138:49)
    at Zip.append (/Users/lukas/Desktop/www/node_modules/archiver/lib/plugins/zip.js:53:15)
    at Archiver._moduleAppend (/Users/lukas/Desktop/www/node_modules/archiver/lib/core.js:172:16)
    at Archiver._onQueueTask (/Users/lukas/Desktop/www/node_modules/archiver/lib/core.js:370:8)
    at /Users/lukas/Desktop/www/node_modules/archiver/node_modules/async/dist/async.js:4045:9
    at process (/Users/lukas/Desktop/www/node_modules/archiver/node_modules/async/dist/async.js:2316:17)

```
